// examples/preact/src/app.tsx
import { render } from 'preact';
import { useState } from 'preact/hooks';
import type { RgPressDetail, RgSelectOption } from '@reglow/elements';
import '@reglow/elements/register';
import '@reglow/preact';
import '@reglow/tokens/css';
import '@reglow/example-theme/demo.css';

const REGIONS = [
  { value: 'icn', label: 'Seoul · ICN edge' },
  { value: 'fra', label: 'Frankfurt · FRA core' },
  { value: 'pdx', label: 'Portland · PDX orbit' },
  { value: 'syd', label: 'Sydney · SYD relay' },
  { value: 'lhr', label: 'London · LHR archive', disabled: true },
] satisfies readonly RgSelectOption[];

const REGION_LABELS = new Map(REGIONS.map((region) => [region.value, region.label]));

interface LaunchSettings {
  readonly projectName: string;
  readonly region: string;
  readonly isPrivate: boolean;
  readonly confidence: number;
}

const INITIAL_SETTINGS: LaunchSettings = {
  projectName: 'Atlas Field Notes',
  region: 'icn',
  isPrivate: true,
  confidence: 4,
};

function PreactLaunchRoom() {
  const [projectName, setProjectName] = useState(INITIAL_SETTINGS.projectName);
  const [region, setRegion] = useState(INITIAL_SETTINGS.region);
  const [isPrivate, setIsPrivate] = useState(INITIAL_SETTINGS.isPrivate);
  const [confidence, setConfidence] = useState(INITIAL_SETTINGS.confidence);
  const [launch, setLaunch] = useState<LaunchSettings>(INITIAL_SETTINGS);
  const [status, setStatus] = useState(
    'Atlas Field Notes is staged in the Seoul orbit. Adjust the draft, then save it.',
  );

  const saveLaunch = (event: CustomEvent<RgPressDetail>) => {
    const nextProjectName = projectName.trim() || 'Untitled Northstar';
    const nextLaunch = { projectName: nextProjectName, region, isPrivate, confidence };

    setProjectName(nextProjectName);
    setLaunch(nextLaunch);
    setStatus(
      `${nextProjectName} saved to ${REGION_LABELS.get(region)} with confidence ${confidence} of 5.`,
    );

    // The detail is fully typed by @reglow/preact. Referencing it here keeps the
    // integration visible without coupling the app to the button's inner DOM.
    if (event.detail.pressed === true) setStatus(`${nextProjectName} is armed and saved.`);
  };

  return (
    <div class="demo-shell">
      <header class="demo-topbar">
        <a class="brand-lockup" href="#launch-settings" aria-label="Reglow Northstar home">
          <span class="brand-mark" aria-hidden="true">
            R
          </span>
          <span>Reglow / Northstar</span>
        </a>
        <span class="framework-pill">Preact · typed raw elements</span>
      </header>

      <main class="demo-main">
        <section class="intro-copy" aria-labelledby="page-title">
          <p class="eyebrow">Launch systems / 04</p>
          <h1 id="page-title">Set the room. Start the orbit.</h1>
          <p>
            A live operations surface built with Preact and Reglow Custom Elements—no wrapper
            components between the product and the platform.
          </p>
        </section>

        <div class="demo-grid">
          <section class="control-panel" id="launch-settings" aria-labelledby="settings-title">
            <div class="panel-heading">
              <div>
                <p class="eyebrow">01 / Configure</p>
                <h2 id="settings-title">Launch settings</h2>
              </div>
              <span aria-hidden="true">NS—24</span>
            </div>

            <form class="form-stack" onSubmit={(event) => event.preventDefault()}>
              <rg-input
                label="Project name"
                description="This becomes the public room title."
                name="projectName"
                required
                value={projectName}
                onInput={(event) => setProjectName(event.currentTarget.value)}
              />

              <rg-select
                label="Launch region"
                description="Choose the closest active relay."
                name="region"
                required
                options={REGIONS}
                value={region}
                onInput={(event) => setRegion(event.currentTarget.value)}
              />

              <div class="field-pair">
                <rg-switch
                  label="Private launch room"
                  description="Invite-only until you publish."
                  name="private"
                  checked={isPrivate}
                  onInput={(event) => setIsPrivate(event.currentTarget.checked)}
                />

                <rg-rating
                  label="Launch confidence"
                  description="Rate operational readiness."
                  name="confidence"
                  value={confidence}
                  onInput={(event) => setConfidence(event.currentTarget.value)}
                />
              </div>

              <div class="action-row">
                <rg-button
                  type="button"
                  variant="solid"
                  tone="brand"
                  size="lg"
                  onrg-press={saveLaunch}
                >
                  Save launch room
                  <span slot="end" aria-hidden="true">
                    ↗
                  </span>
                </rg-button>
                <span>Changes stay local until saved.</span>
              </div>

              <p class="status-note" role="status" aria-live="polite">
                {status}
              </p>
            </form>
          </section>

          <aside class="preview-panel" aria-labelledby="preview-title">
            <div class="preview-orbit" aria-hidden="true">
              <span />
            </div>
            <article class="preview-card">
              <p class="preview-label" id="preview-title">
                Saved launch card
              </p>
              <h2 class="preview-value">{launch.projectName}</h2>
              <p class="preview-meta">
                {REGION_LABELS.get(launch.region)} · {launch.isPrivate ? 'Private' : 'Open room'}
              </p>

              <div class="metric-strip" aria-label="Saved launch metrics">
                <span>
                  <strong>{launch.confidence}/5</strong>
                  <small>confidence</small>
                </span>
                <span>
                  <strong>{launch.isPrivate ? '01' : '∞'}</strong>
                  <small>access mode</small>
                </span>
                <span>
                  <strong>{launch.region.toUpperCase()}</strong>
                  <small>relay</small>
                </span>
              </div>

              <p class="code-note">
                <code>{'<rg-button onrg-press={saveLaunch} />'}</code>
              </p>
            </article>
          </aside>
        </div>

        <p class="footer-note">
          Complex options travel as a property. Native input events keep Preact state in orbit.
        </p>
      </main>
    </div>
  );
}

render(<PreactLaunchRoom />, document.getElementById('app')!);

// examples/svelte/src/App.svelte
<script lang="ts">
  import '@reglow/tokens/css';
  import '@reglow/example-theme/demo.css';
  import { RgButton, RgInput, RgRating, RgSelect, RgSwitch } from '@reglow/svelte';

  const regionOptions = [
    { value: 'seoul', label: 'Seoul · ICN' },
    { value: 'london', label: 'London · LHR' },
    { value: 'new-york', label: 'New York · JFK' },
    { value: 'singapore', label: 'Singapore · SIN' },
  ] as const;

  type LaunchSnapshot = {
    name: string;
    region: string;
    isPrivate: boolean;
    readiness: number;
    revision: number;
  };

  let projectName = $state('Northstar Mobile');
  let region = $state('seoul');
  let isPrivate = $state(true);
  let readiness = $state(4);
  let status = $state('Draft 04 is ready for a final signal check.');
  let launch = $state<LaunchSnapshot>({
    name: 'Northstar Mobile',
    region: 'seoul',
    isPrivate: true,
    readiness: 4,
    revision: 4,
  });

  const previewRegion = $derived(
    regionOptions.find((option) => option.value === launch.region)?.label ?? 'Unassigned region',
  );
  const readinessLabel = $derived(`${launch.readiness}/5 signal confidence`);

  function queueLaunch(): void {
    const normalizedName = projectName.trim() || 'Untitled launch';
    projectName = normalizedName;
    launch = {
      name: normalizedName,
      region,
      isPrivate,
      readiness,
      revision: launch.revision + 1,
    };
    status = `${normalizedName} is queued for ${regionOptions.find((option) => option.value === region)?.label ?? region}.`;
  }
</script>

<div class="demo-shell">
  <header class="demo-topbar">
    <a class="brand-lockup" href="/" aria-label="Northstar Launch Room home">
      <span class="brand-mark" aria-hidden="true">N</span>
      <span>Northstar Launch Room</span>
    </a>
    <span class="framework-pill">Svelte 5 · Reglow</span>
  </header>

  <main class="demo-main">
    <header class="intro-copy">
      <p class="eyebrow">Launch protocol · 08</p>
      <h1>Give the next release<br />a <em>clean trajectory.</em></h1>
      <p>
        Tune the rollout signal, choose a launch region, and stage a release brief without leaving
        the room.
      </p>
    </header>

    <div class="demo-grid">
      <section class="control-panel" aria-labelledby="settings-heading">
        <div class="panel-heading">
          <div>
            <span>Release settings</span>
            <h2 id="settings-heading">Flight brief</h2>
          </div>
          <span>Draft {String(launch.revision).padStart(2, '0')}</span>
        </div>

        <div class="form-stack">
          <RgInput
            bind:value={projectName}
            label="Project name"
            description="Shown on the launch card and status feed."
            placeholder="Name this release"
            clearable
          />

          <RgSelect
            bind:value={region}
            options={regionOptions}
            label="Primary region"
            description="Complex option data is assigned as a live element property."
          />

          <div class="field-pair">
            <RgSwitch
              bind:checked={isPrivate}
              label="Private rollout"
              description="Invite-only until the signal clears."
            />
            <RgRating
              bind:value={readiness}
              label="Signal confidence"
              description="Rate operational readiness."
              max={5}
            />
          </div>

          <div class="action-row">
            <RgButton variant="solid" tone="brand" size="lg" onPress={queueLaunch}>
              Queue launch
            </RgButton>
            <span>↗ Brief updates on press</span>
          </div>

          <p class="status-note" role="status" aria-live="polite">{status}</p>
        </div>
      </section>

      <section class="preview-panel" aria-labelledby="preview-heading">
        <div class="preview-orbit" aria-hidden="true">
          <span></span>
          <span></span>
          <span></span>
        </div>

        <article class="preview-card">
          <p class="preview-label">
            Live output · NL–{String(launch.revision).padStart(2, '0')}
          </p>
          <h2 class="preview-value" id="preview-heading">{launch.name}</h2>
          <p class="preview-meta">
            <span>{previewRegion}</span>
            <span>{launch.isPrivate ? 'Private channel' : 'Public channel'}</span>
          </p>

          <div class="metric-strip" aria-label="Launch metrics">
            <div><span>Window</span><strong>09:40 KST</strong></div>
            <div>
              <span>Audience</span><strong>{launch.isPrivate ? 'Invited' : 'Everyone'}</strong>
            </div>
            <div>
              <span>Readiness</span><strong
                >{'●'.repeat(launch.readiness)}{'○'.repeat(5 - launch.readiness)}</strong
              >
            </div>
          </div>

          <p class="code-note">
            <code>bind:value · bind:checked · onPress</code>&nbsp; keeps {readinessLabel} in sync.
          </p>
        </article>
      </section>
    </div>
    <footer class="footer-note">
      <span>Reglow integration specimen</span>
      <span>Svelte components · typed callbacks · live bindings</span>
    </footer>
  </main>
</div>
